### ISSUE TITLE
`date-fns-tz/format` does not throw RangeError if invalid timezone supplied.

### ISSUE THREAD

**Issue by DeividasBakanas** [marnusw/date-fns-tz#152]
Since v1.1.5 `date-fns-tz/format` does not throw RangeError if invalid timezone supplied. Though README still states:
```
Similar to date-fns/format, when an invalid date or time zone is used a RangeError is thrown.
```

Up to v1.1.5 code
```
format(new Date(), 'xxxxx', { timeZone: 'X/Y' })
```
produced an error (check at https://stackblitz.com/edit/node-ewhdjy?file=index.js)
```
RangeError: Invalid time zone specified: X/Y
    at new DateTimeFormat (<anonymous>)
    at getDateTimeFormat (/home/projects/node-jqjxm2/node_modules/date-fns-tz/_lib/tzTokenizeDate/index.js:77:10)
    at tzTokenizeDate (/home/projects/node-jqjxm2/node_modules/date-fns-tz/_lib/tzTokenizeDate/index.js:13:13)
    at calcOffset (/home/projects/node-jqjxm2/node_modules/date-fns-tz/_lib/tzParseTimezone/index.js:81:35)
    at tzParseTimezone (/home/projects/node-jqjxm2/node_modules/date-fns-tz/_lib/tzParseTimezone/index.js:68:18)
    at Object.x (/home/projects/node-jqjxm2/node_modules/date-fns-tz/format/formatters/index.js:51:74)
    at eval (/home/projects/node-jqjxm2/node_modules/date-fns-tz/format/index.js:336:99)
    at Array.reduce (<anonymous>)
    at format (/home/projects/node-jqjxm2/node_modules/date-fns-tz/format/index.js:335:25)
    at Object.eval (/home/projects/node-jqjxm2/index.js:8:15)
```

Since v1.1.5 it produces `+00:00` (check at https://stackblitz.com/edit/node-ykcwvj?file=index.js) and since v1.2.0 it produces `+NaN:NaN` (check at https://stackblitz.com/edit/node-jqjxm2?file=index.js).

Expected behavior - throw an error if invalid timezone supplied.

**Comment by marnusw** [comment]
Thanks for the detailed report with examples @DeividasBakanas. Fixed in `v1.3.0`.
