### ISSUE TITLE
Update types for format to match date-fns

### ISSUE THREAD

**Issue by bmeverett** [marnusw/date-fns-tz#198]
I am currently getting an error when passing in a string to `format`.

```
Starting with v2.0.0-beta.1 date-fns doesn't accept strings as date arguments. 
Please use `parseISO` to parse strings. See: https://git.io/fjule
```

The types say it accepts `Date |  Number | String`, however it looks like this just calls out to `date-fns` [here](https://github.com/marnusw/date-fns-tz/blob/master/src/format/index.js#L344). The `date-fns` library only accepts [Date | Number](https://date-fns.org/v2.29.2/docs/format#arguments).

Should we update the types of format to only accept `Date | Number` to match `date-fns`, or should we internally use `parseISO` in this libraries format function?

Happy to make a PR with whatever is decided!

**Comment by marnusw** [comment]
`parseISO` is a massive function which I don't want to use.

Does this actually throw an error when passing in a string date? If so the function is broken and what we don't won't really be a breaking change either way, since no one will be using this "feature".

I think we can change the types to `Date | Number`.

**Comment by bmeverett** [comment]
Yea it fails with `Invalid time value`

```
"RangeError: Invalid time value\n   
   at format .format (/app/node_modules/date-fns/format/index.js:392:11 undefined)\n   
   at format .format (/app/node_modules/date-fns-tz/format/index.js:351:29 undefined)\n    at /app/src/experiences/schedule/schedule.functions.ts:404:40\n   
   at Array.forEach (<anonymous> undefined)\n   
   at groupAndSortEventsByDay .groupAndSortEventsByDay (/app/src/experiences/schedule/schedule.functions.ts:399:10 undefined)\n   
   at Object.renderScheduleSections (/app/src/experiences/schedule/schedule.functions.ts:296:26 undefined)\n   
   at ScheduleService.getPartialScheduleTabResult (/app/src/experiences/schedule/schedule.service.ts:168:36 undefined)\n   
   at processTicksAndRejections .processTicksAndRejections (node:internal/process/task_queues:96:5 undefined)\n   
   at ScheduleController.getScheduleTabDatePartialExperience (/app/src/experiences/schedule/schedule.controller.ts:216:12 undefined)"
```

**Comment by marnusw** [comment]
I'll merge a PR changing to the types then, thanks for volunteering. If you think the readme needs updating and have the time please change that too.
